//Diccionario de terminos cambiar lo que se necesite aqui

const Diccionario = {
    alertaSalir: "Estás a punto de salir del formulario. Los cambios que has realizado no se guardarán.",
    anio: "2025",
    apellidoMaterno: "Apellido Materno",
    apellidoPaterno: "Apellido Paterno",
    cambiarContraseña: "Cambiar Contraseña",
    cancelar: "Cancelar",
    carrera: "Carrera",
    centrosUniversitarios: "Centros Universitarios",
    cerrarSesion: "Cerrar Sesión",
    cerrarSesionPregunta: "¿Estás seguro de que quieres cerrar sesión?",
    codigo: "Código",
    codigoExiste: "Codigo ya registrado",
    confirmar: "Confirmar",
    confirmarCambio: "Confirmar cambio de datos",
    confirmarCambioContraseña: "Confirmar Cambio de Contraseña",
    confirmarContraseña: "Confirmar Contraseña",
    contrasenia: "Contraseña",
    correoElectronico: "Correo Electronico",
    correoNoValido: "Por favor, ingresa un correo electrónico válido.",
    datosGenerales: "Datos generales",
    dependencia: "Dependencia",
    enviarSolicitud: "Enviar Solicitud",
    formatoCodigoNoValido: "El formato del codigo no es valido",
    ingresaCodigo: "Ingresa tu código",
    ingresar: "Ingresar",
    loggeado: "Loggeado",
    login: "Login",
    modalidadAcademico: "Academico",
    modalidadEstudiante: "Estudiante",
    nombramiento: "Nombramiento",
    nombre: "Nombre",
    nombreCompleto: "Nombre Completo",
    nombres: "Nombre/s",
    noTienesCuenta: "¿No tienes cuenta? Solicitala aquí",
    nuevaContraseña: "Nueva Contraseña",
    registro: "Registro",
    registroAcademico:"Registro Academico",
    registroEstudiante:"Registro Estudiante",
    reiniciarContenido: "Reiniciar Contenido",
    seleccioneCarrera: "Seleccione Carrera",
    seleccioneDependencia: "Seleccione Dependencia",
    seleccioneNombramiento: "Seleccione Nombramiento",
    tienesProblemaContactanos: "Tienes un problema ¡Contactanos Aqui!",
    yaTienesCuenta: "¿Ya tienes cuenta? Inicia Sesion aquí",
};

export default Diccionario;
